Repository retaildevcrews/ngsa-java, pull requests merged in 2021-06, with the labels that each got.

#7 Benchmark Controller: problem+json response for invalid parameter
  src/main/java/com/cse/ngsa/app/controllers/BenchmarkController.java
  src/main/java/com/cse/ngsa/app/utils/InvalidParameterResponses.java
  src/main/java/com/cse/ngsa/app/utils/ParameterValidator.java
Labels: REFACTOR, first-good-issue

#8 Added X-Load-Feedback header for bursting
  src/main/java/com/cse/ngsa/app/controllers/HealthzController.java
  src/main/java/com/cse/ngsa/app/utils/CommonUtils.java
  src/main/resources/application.properties
Labels: Enhancement, REFACTOR

#10 Added Upsert and Delete Operations
  src/main/java/com/cse/ngsa/app/controllers/MoviesController.java
  src/main/java/com/cse/ngsa/app/dao/MoviesDao.java
  src/main/java/com/cse/ngsa/app/models/Movie.java
  src/main/java/com/cse/ngsa/app/utils/InvalidParameterResponses.java
  src/main/java/com/cse/ngsa/app/utils/ParameterValidator.java
Labels: Enhancement

#13 Bugfix/request logger
  pom.xml
  src/main/java/com/cse/ngsa/app/middleware/RequestLogger.java
  src/test/resources/log4j2.properties
Labels: Bug

#12 Abassey readme
  README.md
Labels: Documentation

#16 Abassey/usage
  ngsa/src/main/java/com/cse/ngsa/app/NgsaJavaApplication.java
  ngsa/src/main/java/com/cse/ngsa/app/utils/CommonUtils.java
Labels: Bug

#21 Build Fail Fix: jforg removed snapshot builds of several Springfox artifacts
  ngsa/pom.xml
Labels: Bug, CI/CD

#22 Feature/vscode dbg settings
  docs/vscode-template/launch.json
  docs/vscode-template/tasks.json
Labels: DevExperience

#24 Add LodeRunner test to ngsa-java CI/CD on Pull Request
  .github/workflows/ngsa-pr.yaml
  .github/workflows/ngsa.yaml
  Dockerfile
Labels: CI/CD
