Repository retaildevcrews/ngsa-java, pull requests merged in 2021-08, with the labels that each got.

#50 updated Codespaces build
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/library-scripts/azcli-debian.sh
  .devcontainer/library-scripts/docker-debian.sh
  .devcontainer/library-scripts/maven-debian.sh
  .devcontainer/on-create.sh
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/EngineeringPractices.md
  .github/SECURITY.md
  .github/SUPPORT.md
  .github/WorkingAgreement.md
  .github/workflows/ngsa-devcontainer.yaml
  README.md
Labels: Bug

#53 Update README.md to include zone and region
  README.md
Labels: Documentation

#54 Enable autogitops in ngsa-java
  .github/workflows/ngsa.yaml
  autogitops/autogitops.json
  autogitops/ngsa-preprod.yaml
Labels: CI/CD

#56 Benchmark controller fix
  ngsa/src/main/java/com/cse/ngsa/app/Constants.java
  ngsa/src/main/java/com/cse/ngsa/app/controllers/BenchmarkController.java
  ngsa/src/main/java/com/cse/ngsa/app/utils/ParameterValidator.java
Labels: Bug
