Repository retaildevcrews/ngsa-java, pull requests merged in 2021-07, with the labels that each got.

#29 Request Logger CLI Args and level change
  ngsa/src/main/java/com/cse/ngsa/app/controllers/ActorsController.java
  ngsa/src/main/java/com/cse/ngsa/app/controllers/BenchmarkController.java
  ngsa/src/main/java/com/cse/ngsa/app/controllers/Controller.java
  ngsa/src/main/java/com/cse/ngsa/app/controllers/FeaturedController.java
  ngsa/src/main/java/com/cse/ngsa/app/controllers/GenresController.java
  ngsa/src/main/java/com/cse/ngsa/app/controllers/MoviesController.java
  ngsa/src/main/java/com/cse/ngsa/app/controllers/VersionController.java
  ngsa/src/main/java/com/cse/ngsa/app/middleware/RequestLogger.java
  ngsa/src/main/java/com/cse/ngsa/app/services/volumes/Secrets.java
  ngsa/src/main/java/com/cse/ngsa/app/services/volumes/VolumeSecretService.java
  ngsa/src/main/resources/application.properties
  ngsa/src/main/resources/log4j2.properties
  ngsa/src/test/resources/application.properties
Labels: NGSAJava

#32 Updated java.home to use zulu
  .devcontainer/devcontainer.json
Labels: Bug

#33 Reduce Startup and CI Verbosity
  .github/workflows/ngsa-pr.yaml
  .github/workflows/ngsa.yaml
  Dockerfile
  ngsa/src/main/resources/logback.xml
Labels: CI/CD, NGSAJava

#30 Implement Prometheus endpoint
  .devcontainer/devcontainer.json
  docs/vscode-template/launch.json
  docs/vscode-template/tasks.json
  ngsa/pom.xml
  ngsa/src/main/java/com/cse/ngsa/app/middleware/RequestLogger.java
  ngsa/src/main/java/com/cse/ngsa/app/utils/CpuMonitor.java
  ngsa/src/main/java/com/cse/ngsa/app/utils/QueryUtils.java
  ngsa/src/main/resources/application.properties
Labels: DevExperience, Enhancement, NGSAJava

#34 Fixed Version Controller Unittest
  ngsa/src/test/java/com/cse/ngsa/app/controllers/VersionControllerTest.java
Labels: Bug

#43 Update devcontainer to use ghcr.io
  .devcontainer/devcontainer.json
  .github/workflows/ngsa-devcontainer.yaml
Labels: CI/CD, Enhancement, NGSAJava
